#!/bin/bash

HOOK_TYPE="pre-push"
HOOKS_FOLDER="$(dirname "$0")/${HOOK_TYPE}.d"

for hook in ${HOOKS_FOLDER}/*; do
    ./${hook}
    RESULT=$?
    if [ $RESULT != 0 ]; then
        echo "${HOOK_TYPE}/${hook} returned non-zero: ${RESULT}, abort commit"
        exit $RESULT
    fi
done

exit 0