#!/usr/bin/env bash
set -uo pipefail

readonly HOOK_TYPE="pre-push"
readonly HOOKS_FOLDER="$(dirname "$0")/${HOOK_TYPE}.d"

readonly RUN_ALL_TESTS=false
EXIT_STATUS=0

HOOKS=$(find "${HOOKS_FOLDER}" -type f -executable)

for hook in ${HOOKS}; do
    # hooks that begin with an underscore are skipped
    if [[ $(basename "${hook}") == _* ]]; then
        echo "> skipping ${HOOK_TYPE}/${hook}"
        continue
    fi
    ./"${hook}" "$@"
    RESULT=$?
    if [ ${RESULT} != 0 ]; then
        EXIT_STATUS=${RESULT}
        echo "${HOOK_TYPE}/${hook} returned non-zero: ${RESULT}"
        if [[ "${RUN_ALL_TESTS}" = false ]]; then
            exit ${EXIT_STATUS}
        fi
    fi
done

exit ${EXIT_STATUS}
