#!/usr/bin/env bash
set -uo pipefail

readonly HOOK_TYPE="pre-commit"
readonly HOOKS_FOLDER="$(dirname "$0")/${HOOK_TYPE}.d"

readonly RUN_ALL_TESTS=false
EXIT_STATUS=0

HOOKS=$(find "${HOOKS_FOLDER}" -type f -executable)

for HOOK_PATH in ${HOOKS}; do
    # hooks that begin with an underscore are skipped
    HOOK_NAME=$(basename "${HOOK_PATH}")
    if [[ "${HOOK_NAME}" == _* ]]; then
        echo "> skipping ${HOOK_NAME}"
        continue # go to next hook
    fi
    ./"${HOOK_PATH}"
    RESULT=$?
    if [ ${RESULT} != 0 ]; then
        EXIT_STATUS=${RESULT}
        echo "${HOOK_TYPE}/${HOOK_NAME} returned non-zero: ${RESULT}"
        if [[ "${RUN_ALL_TESTS}" = false ]]; then
            exit ${EXIT_STATUS}
        fi
    fi
done

exit ${EXIT_STATUS}
